branch-defaults:
  master:
    environment: rails-beanstalk-env
    group_suffix: null
global:
  application_name: your-kitchen2
  branch: null
  default_ec2_keyname: null
  default_platform: Ruby 2.3 (Puma)
  default_region: us-west-1
  profile: null
  repository: null
  sc: git
